In [3]:
# this is to import panda library which has functions needed to do dataset operations like read csv excel file and do database operations. pandas are assigned as pd here
import pandas as pd

In [5]:
dataset=pd.read_csv("Salary_Data.csv") # In panda (pd) class read_csv function is used to read our dataset file and store in varibale dataset

In [6]:
dataset #print dataset

    YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [7]:
independent=dataset[["YearsExperience"]] # As we found YearsExperience as input during our requirement phase. Assigning the YearsExperience column in to variable called independent 
independent

In [10]:
dependent=dataset[["Salary"]] # As we found Salary as output during our requirement phase. Assigning the Salary column in to variable called dependent 
dependent

      Salary
0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
5    56642.0
6    60150.0
7    54445.0
8    64445.0
9    57189.0
10   63218.0
11   55794.0
12   56957.0
13   57081.0
14   61111.0
15   67938.0
16   66029.0
17   83088.0
18   81363.0
19   93940.0
20   91738.0
21   98273.0
22  101302.0
23  113812.0
24  109431.0
25  105582.0
26  116969.0
27  112635.0
28  122391.0
29  121872.0

In [15]:
from sklearn.model_selection import train_test_split # We use sklearn library, model-selection function and import only train_test_split function  to split training set and test set
X_train,X_test,y_train,y_test=train_test_split(independent, dependent, test_size=0.30,random_state=0) 
#passing the independent & dependent parameter to this function to split train set as 70% and test set as 30%, using test_ size=0.30 
#Assign variables for each set (X_train is 70% of independent(input) dataset, y_train is 70% of dependent(output) dataset.
#Assign variables for each set (X_test is 30% of independent(input) dataset , y_test is 30% of dependent(output) dataset

In [16]:
from sklearn.linear_model import LinearRegression # importing Linear Regression model from sklearn
regressor=LinearRegression() # LinearRegression non parameterized function is stored in regressor variable 
regressor.fit(X_train,y_train) # calling fit function using access operator (.), Passing Training input and output
#this step is the learning process of the model that we train

LinearRegression()

In [17]:
weight=regressor.coef_ # To check weight/slope value we use .coef_ function
weight

array([[9360.26128619]])

In [18]:
bais=regressor.intercept_ # To check bais value we use .intercept_
bais

array([26777.3913412])

In [21]:
y_pred=regressor.predict(X_test) # calling predict method to get the output for X_test. This is used to cross check the model

In [23]:
from sklearn.metrics import r2_score # from Sklearn metrics import r2_score to find r2_score 
r_score=r2_score(y_test,y_pred)
# using r2score function by passing (y_test (actual_output), y_pred(predicted_output)) as parameter to find r2 value

In [24]:
r_score # as r_score less than 1 , out model is good one.

0.9740993407213511

In [26]:
import pickle #importing pickle to same our model
filename="Finalized_model_linear.sav" # initilizing the file name to be saved as Finalized_model_linear.sav

In [28]:
pickle.dump(regressor,open(filename,'wb'))# dumping our model which is in regressor to the filename with Write

In [30]:
loaded_model=pickle.load(open("Finalized_model_linear.sav",'rb')) #deploy the model using pickle.load by opening the file with read 
result=loaded_model.predict([[15]]) # validate the model with input 
result #print result

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([[167181.3106341]])